### PR TITLE
fix: return hidden only for writer on export

### LINKED ISSUE #957: [Bug] should not export hidden item

### PR DESCRIPTION
**Pull request by pyphilia**
fix #957

### CODE REVIEW

File: src/services/item/plugins/importExport/service.ts [hunk 1]
```diff
@@ -321,6 +321,7 @@ export class ImportExportService {
       archiveRootPath: rootPath,
       archive,
     }).catch((error) => {
+      console.log(error);
```
Comment (spaenleh) [inline src/services/item/plugins/importExport/service.ts:324]: Keep this ? Maybe use fastify logger ?

**Review by spaenleh — APPROVED** [review]
Yeah !
