### PR TITLE
fix: export a zip use stream

### LINKED ISSUE #516: [Export-zip] Export empty folders

### LINKED ISSUE #537: [export-zip] No space left on device
Possible workaround: https://www.npmjs.com/package/yauzl

### PR DESCRIPTION
**Pull request by pyphilia**
This PR refactor `/zip-export` to use `yazl`. This library is supposed to handle streams, so we don't need to download all the files temporarly.

Currently h5p still saves its own temporary file. But this can be handled in a refactor for the download method of `FileService`.

close #537 
close #516

### CODE REVIEW

File: src/services/item/plugins/importExport/service.ts [hunk 1]
```diff
@@ -220,10 +222,9 @@ export class ImportExportService {
         const { mimetype } =
           (item.extra[ItemType.S3_FILE] as S3FileItemExtra) ||
           (item.extra[ItemType.LOCAL_FILE] as LocalFileItemExtra);
-        const fileStream = await this.fileItemService.download(actor, repositories, {
-          fileStorage,
+        const url = (await this.fileItemService.download(actor, repositories, {
           itemId: item.id,
-        });
+        })) as string;
```
Comment (pyphilia) [inline src/services/item/plugins/importExport/service.ts:227]: Casting necessary because the method `download` is quite a mess. To be handled in another PR.

File: src/services/item/plugins/importExport/service.ts [hunk 2]
```diff
@@ -200,17 +201,18 @@ export class ImportExportService {
       reply;
       item: Item;
```
Comment (dialexo) [inline src/services/item/plugins/importExport/service.ts:202]: Is it possible to type it here as a `DiscriminatedItem`? This would allow the extras to be typed correctly below without the need to cast them specifically

**Review by dialexo — CHANGES_REQUESTED** [review]

File: src/services/item/plugins/importExport/service.ts (hunk 2 above)
Comment (pyphilia) [reply src/services/item/plugins/importExport/service.ts:202]: I will do the change, but it does not fit well with the Item repository. For example get an item return type is `Item` which does not fit with `DiscriminatedItem`. Changing this would result in changes everywhere in the project. 

So I've opted for casting to `Item` instead, which is indeed better.

**Comment by pyphilia** [comment]
I did the changes you requested! I moved some bunch of code to the controller, which is quite nice I think. 
Only regret is the `fileStorage` I don't think I can delete unless the stream is sent (so I had to "hack" around). But this will disappear once we refactor the h5p/file service.

File: src/services/item/plugins/importExport/service.ts [hunk 3]
```diff
@@ -300,37 +288,31 @@ export class ImportExportService {
...
-    { itemId, reply }: { itemId: UUID; reply: FastifyReply },
+    {
+      item,
+      reply,
+      fileStorage,
+    }: { fileStorage: string; item: Item; reply: FastifyReply; log?: FastifyBaseLogger },
   ) {
-    // check item and permission
-    const item = await this.itemService.get(actor, repositories, itemId);
-
```
Comment (dialexo) [inline src/services/item/plugins/importExport/service.ts:307]: Is the check not required anymore or was it moved?

File: src/services/item/plugins/importExport/service.ts [hunk 4]
```diff
@@ -300,37 +288,31 @@ export class ImportExportService {
...
     // init archive
-    const archive = archiver.create('zip', { store: true });
-    archive.on('warning', function (err) {
+    const archive = new yazl.ZipFile();
+    archive.outputStream.on('warning', function (err) {
       if (err.code === 'ENOENT') {
         // log.debug(err);
       } else {
         throw err;
       }
```
Comment (dialexo) [inline src/services/item/plugins/importExport/service.ts:304]: Not sure what error is handled here?

File: src/services/item/plugins/importExport/service.ts [hunk 5]
```diff
@@ -300,37 +288,31 @@ export class ImportExportService {
...
     });
-    archive.on('error', function (err) {
+    archive.outputStream.on('error', function (err) {
       throw err;
     });
```
Comment (dialexo) [inline src/services/item/plugins/importExport/service.ts:308]: Is this useful?

**Review by dialexo — APPROVED** [review]
I have a few questions but otherwise LGTM 🥮

File: src/services/item/plugins/importExport/service.ts (hunk 3 above)
Comment (pyphilia) [reply src/services/item/plugins/importExport/service.ts:307]: It moved to the controller (I needed the name, it's also better to check the permission before creating the filestorage).

File: src/services/item/plugins/importExport/service.ts (hunk 5 above)
Comment (pyphilia) [reply src/services/item/plugins/importExport/service.ts:308]: Not sure, but I think it doesn't hurt?

**Review by dialexo — APPROVED** [review]
