### PR TITLE
fix: remove deprecated values for cc licenses

### LINKED ISSUE #1073: Migrates Old CC

### PR DESCRIPTION
**Pull request by pyphilia**
Hopefully fix 

```
GET /item-memberships
The value of 'item#/properties/settings/properties/ccLicenseAdaption' does not match schema definition.
```
close #1073

### CODE REVIEW

File: src/migrations/1733844120221-cc-license-values.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import { MigrationInterface, QueryRunner } from 'typeorm';
+
+export class Migrations1733844120221 implements MigrationInterface {
+  name = 'cc-license-values-1733751673963';
+
+  public async up(queryRunner: QueryRunner): Promise<void> {
+    // remove ccLicenseAdaption keys for empty values
+    await queryRunner.query(
+      `update item set settings = settings::jsonb - 'ccLicenseAdaption' where length((settings::jsonb->'ccLicenseAdaption')::text) = 2`,
```
Comment (spaenleh) [inline src/migrations/1733844120221-cc-license-values.ts:9]: Same comment about using `->>` here ?

File: src/migrations/1733844120221-cc-license-values.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    );
+    // remove deprecated values alike to CC BY-NC-SA
+    await queryRunner.query(
+      `update item set settings = jsonb_set(settings::jsonb, '{ccLicenseAdaption}'::text[], '"CC BY-NC-SA"'::jsonb) where (settings::jsonb->'ccLicenseAdaption')::text = '"alike"';`,
+    );
+    // remove deprecated values allow to CC BY-NC
+    await queryRunner.query(
+      `update item set settings = jsonb_set(settings::jsonb, '{ccLicenseAdaption}'::text[], '"CC BY-NC"'::jsonb) where (settings::jsonb->'ccLicenseAdaption')::text = '"allow"';`,
```
Comment (spaenleh) [inline src/migrations/1733844120221-cc-license-values.ts:17]: Not tested but maybe:

```suggestion
      `update item set settings = jsonb_set(settings::jsonb, '{ccLicenseAdaption}'::text[], '"CC BY-NC"'::jsonb) where settings::jsonb->>'ccLicenseAdaption' = 'allow';`,
```

**Review by spaenleh — APPROVED** [review]
Looks good ! Not sure If we can simplify the SQL a bit. I know working with jsonb can be tricky.
