### PR TITLE
fix: replace non breaking spaces from link metadata title

### LINKED ISSUE #1338: [Link metadata] replace special white space by normal spaces when returning the page title

### PR DESCRIPTION
**Pull request by pyphilia**
Replace non classic spaces from link metadata:
-  non breaking spaces
- tab
- breaking spaces

close #1338

### CODE REVIEW

**Comment by MatveyK** [comment]
Shouldn't we just filter out all "weird" Unicode space characters ? There's a lot of them and we already do this for the usernames.

See the `USERNAME_FORBIDDEN_CHARS_REGEX` in `@graasp/sdk`.

**Comment by pyphilia** [comment]
Good idea, I've added the unicode characters in the regex, but it did not include non-breaking spaces nor tabs.

File: src/services/item/plugins/embeddedLink/service.ts [hunk 1]
```diff
@@ -90,8 +90,12 @@ export class EmbeddedLinkItemService extends ItemService {
       const { meta = {}, html, links = [] } = (await response.json()) as IframelyResponse;
       const { title, description } = meta;
 
+      // does not accept weird unicode characters, non-breaking spaces, tabs, breaking lines
+      const r = new RegExp('[ \t\u{0000}-\u{001F}\u{007F}-\u{009F}]', 'gu');
+
       return {
-        title: title?.trim(),
+        // fix non-breaking spaces
```
Comment (pyphilia) [inline src/services/item/plugins/embeddedLink/service.ts:97]: remove this comment

**Review by spaenleh — APPROVED** [review]
