### PR TITLE
fix: filter out recycled items on get geolocation

### LINKED ISSUE #804: cannot return geolocation if one item is deleted

### PR DESCRIPTION
**Pull request by pyphilia**
fix #804

### CODE REVIEW

File: src/services/item/plugins/geolocation/repository.ts [hunk 1]
```diff
@@ -71,7 +71,8 @@ export class ItemGeolocationRepository {
 
     const geoloc = this.repository
       .createQueryBuilder('ig')
-      .leftJoinAndSelect('ig.item', 'item')
+      // inner join to filter out recycled items
+      .innerJoinAndSelect('ig.item', 'item')
```
Comment (spaenleh) [inline src/services/item/plugins/geolocation/repository.ts:75]: Ah yes ... this is the real pain of using the soft-delete feature ... I recall having to hunt down usage like these with Morgan ... Not fun.

**Review by spaenleh — APPROVED** [review]
Looks good, but maybe the `omit` was not such a great idea after all... see the type errors you get...
