### PR TITLE
fix: password reset token should be single use

### LINKED ISSUE #1532: [BUG] Token used for password reset request can be used multiple times
It is possible to use a reset password link multiple times.

The key is incorrectly removed from redis.

### PR DESCRIPTION
**Pull request by spaenleh**
close #1532

### CODE REVIEW

File: src/services/auth/plugins/password/service.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export class MemberPasswordService {
     if (!id) {
       return;
     }
-    await this.redis.del(uuid);
+    await this.redis.del(`${REDIS_PREFIX}${uuid}`);
```
Comment (pyphilia) [inline src/services/auth/plugins/password/service.ts:88]: Wouldn't it be clearer if you have a private fn to build the prefix? So you can reuse at get, post and delete.

**Review by pyphilia — APPROVED** [review]
Thanks for the quick fix! Maybe my comment is relevant before merging.
