### PR TITLE
fix: creator serialisation issue

### LINKED ISSUE #1031: Creator is not serialized correctly because of incorrect return code in schema
A miss-match between the effective return codes and the return code specified in the schema makes the serialisation not work on item create.

The effective return code is 200 while the schema expected response code is 201, the schema is not used for the response.

### PR DESCRIPTION
**Pull request by spaenleh**
fix #1031

### CODE REVIEW

File: src/services/item/service.ts [hunk 1]
```diff
@@ -322,6 +322,7 @@ export class ItemService {
       memberships.map(({ item }) => item),
       resultOfMembership,
     );
+    this.log.debug(packedItems);
```
Comment (pyphilia) [inline src/services/item/service.ts:325]: Remove?

**Review by pyphilia — APPROVED** [review]
I guess we should also decide on what format we want to use, we still have this strange mix of fluent-schema and ajv..
