### PR TITLE
fix: update schema for current account

### LINKED ISSUE #1534: GET /current fails for guest user
Logging in as a guest will throw /current because of schema validation.

### PR DESCRIPTION
**Pull request by pyphilia**
Based on  https://github.com/graasp/graasp/pull/1539

fix #1534

### CODE REVIEW

File: test/setup.ts
Comment (spaenleh) [inline test/setup.ts:1]: Should this file be in the `/test` folder or inside `/src/services/member/test` ?

File: src/services/member/test/index.test.ts [hunk 1]
```diff
@@ -47,11 +57,28 @@ describe('Member routes tests', () => {
...
+      expect(m.name).toEqual(member.name);
+      expect(m.email).toEqual(member.email);
+      expect(m.id).toEqual(member.id);
       expect(m.password).toBeUndefined();
+    });
+
+    it('Returns successfully if signed in as guest', async () => {
+      const { guest } = await setupGuest(app);
+
+      mockAuthenticate(guest);
```
[the remark this answers is not in the document]
Comment (spaenleh) [reply src/services/member/test/index.test.ts:69]: For this we should probably rely on making tests with support for a session (if we want to use the cookie based authentication). I think `app.inject` is better suited to test either individual endpoints or API that use JWT authentication that can be passed in a header.

File: src/services/member/schemas.ts [hunk 2]
```diff
@@ -240,7 +281,7 @@ export const updateOne = {
   params: entityIdSchemaRef,
   body: updateMemberRequiredOneSchemaRef,
   response: {
-    [StatusCodes.OK]: currentMemberSchemaRef,
+    [StatusCodes.OK]: currentAccountSchemaRef,
```
Comment (spaenleh) [inline src/services/member/schemas.ts:284]: I am thinking that the frontend usually does not make use of the return values from POST and PATCH calls (unless we use `mutateAsync` so maybe we could spare the returns and rely on the stale fetching from the hooks ? since typeorm is also not very useful when we want to get the value we have to perform a get after the update. Maybe something to think about for later.

**Review by spaenleh — CHANGES_REQUESTED** [review]
Changes look good.

There is just something I don't quite get. For anyone on graasp `account` is supposed to be other users right ? So it should only contain `id, name`.

We only expose more of these properties when we are giving the **current** member. In these cases it can be an `individual` or a `guest`.

I think we should have these concepts clear. I think the issue is that in terms of entities the account is the most complete one. But in terms of what the API and types for clients are. Account is really the most simple `id,name` one. 
I think the schema names should represent this.

File: test/setup.ts
Comment (pyphilia) [reply test/setup.ts:1]: I envision it as a reusable setup, so that's why it's in test. But I can move it to member. What do you think?

**Comment by pyphilia** [comment]
From my understanding:
- `Account` can either be a `Guest` or a `Member`. It's usually what we get for an `account` property (id, name)
- `CompleteX` is a type in `graasp/sdk`, sometimes used in the backend, but more for its type. But it is was what was used for typing `/current`. So I instead called it `CurrentX` in my PR.
- `AugmentedX` is what is used for memberships, since we needed more data to display the table (eg: email).

`Account` is not the most complete type. I think even when using typeorm, you only receive the common properties, since it's based on the entity.

Let me know if you need more explanations.

**Comment by spaenleh** [comment]
@pyphilia Your explanation makes sens. I guess I was thrown off by the use of both `account` and `currentAccount`.

**Review by spaenleh — APPROVED** [review]
