### PR TITLE
fix: throw for undefined member id in token

### LINKED ISSUE #543: Handle undefined member id in token

### PR DESCRIPTION
**Pull request by pyphilia**
This PR fix the undefined member id in token by:
- using the member repository `get` instead of raw `findOneById`
- refactor auth utils in a dedicated file + `AuthService` (probably we don't need the decoration anymore). It's still confused because we have many functions doing "similar" logic , but I've left major refactor for later
- regression tests + unit tests of auth utils

Additionally:
- All other functions using  `findOneById` have an additional check over id

close #543

### CODE REVIEW

File: src/services/auth/plugins/magicLink/service.ts [hunk 1]
```diff
@@ -49,10 +49,13 @@ export class MagicLinkService {
     }
   }
 
-  async auth(actor: Actor, repositories: Repositories, token) {
+  async auth(actor: Actor, repositories: Repositories, token: string) {
     try {
       // verify and extract member info
-      const result = await promisifiedJwtVerify(token, JWT_SECRET, {});
+      const result = (await promisifiedJwtVerify(token, JWT_SECRET, {})) as jwt.JwtPayload;
```
Comment (dialexo) [inline src/services/auth/plugins/magicLink/service.ts:55]: Info: why is the cast required here? Consider adding a comment

File: src/services/auth/plugins/magicLink/service.ts [hunk 2]
```diff
@@ -49,10 +49,13 @@ export class MagicLinkService {
...
+      // pre test the user existence to avoid providing a key
+      await repositories.memberRepository.get(result.id);
```
Comment (dialexo) [inline src/services/auth/plugins/magicLink/service.ts:57]: Info: This will throw if there is no member?

File: src/services/auth/plugins/mobile/mobile.test.ts [hunk 3]
```diff
@@ -310,7 +307,7 @@ describe('Mobile Endpoints', () => {
 
     it('Fail to authenticate if verifier and challenge do not match', async () => {
       const member = await saveMember(BOB);
-      const t = jwt.sign({ id: member.id }, JWT_SECRET);
+      const t = jwt.sign({ sub: member.id }, JWT_SECRET);
```
Comment (dialexo) [inline src/services/auth/plugins/mobile/mobile.test.ts:310]: Info: why did the property name change?

File: src/services/auth/plugins/mobile/service.ts [hunk 4]
```diff
@@ -89,6 +90,9 @@ export class MobileService {
         throw new ChallengeFailed();
       }
 
+      // pre test the user existence to avoid providing a key
+      await repositories.memberRepository.get(memberId);
```
Comment (dialexo) [inline src/services/auth/plugins/mobile/service.ts:94]: Same question as above

File: src/services/auth/service.ts [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+    const { challenge, url } = options;
+
+    // generate token with member info and expiration
+    const token = await promisifiedJwtSign({ sub: member.id, challenge }, JWT_SECRET, {
+      expiresIn: `${REGISTER_TOKEN_EXPIRATION_IN_MINUTES}m`,
+    });
+
+    const redirectionUrl = getRedirectionUrl(url);
+    const linkPath = challenge ? '/m/deep-link' : '/auth';
+    const link = new URL(`${linkPath}?t=${token}&url=${redirectionUrl}`, PUBLIC_URL).toString();
```
Comment (dialexo) [inline src/services/auth/service.ts:53]: Arf this will mean a rebase #539. But nevermind, I'll merge from main.

File: src/services/auth/service.ts [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+    const { challenge, lang, url } = options;
+
+    // generate token with member info and expiration
+    const token = await promisifiedJwtSign({ sub: member.id, challenge }, JWT_SECRET, {
+      expiresIn: `${LOGIN_TOKEN_EXPIRATION_IN_MINUTES}m`,
+    });
+
+    const redirectionUrl = getRedirectionUrl(url);
+    const linkPath = challenge ? '/m/deep-link' : '/auth';
+    const link = new URL(`${linkPath}?t=${token}&url=${redirectionUrl}`, PUBLIC_URL).toString();
```
Comment (dialexo) [inline src/services/auth/service.ts:84]: Note to self: same here

File: src/services/auth/utils.test.ts [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+import { fetchMemberInSession, verifyMemberInAuthToken, verifyMemberInSession } from './utils';
+
+const buildRequest = (memberId?: string) =>
+  ({
+    session: {
+      get: () => memberId,
+      delete: jest.fn(),
+    },
+    log: { warn: jest.fn() },
+  } as unknown as FastifyRequest & { member?: Member });
```
Comment (dialexo) [inline src/services/auth/utils.test.ts:21]: Not sure about the types here. Is it for testing purposes only?

**Review by dialexo — APPROVED** [review]
Thank you for your work :partying_face: looks much cleaner and more robust now. I just have a few questions, which answers could be useful code comments.

File: src/services/auth/plugins/mobile/mobile.test.ts (hunk 3 above)
Comment (pyphilia) [reply src/services/auth/plugins/mobile/mobile.test.ts:310]: It was false in the test 🥲

File: src/services/auth/utils.test.ts (hunk 7 above)
Comment (pyphilia) [reply src/services/auth/utils.test.ts:21]: Yes, test only. It's not easy to mock a fastify request.
