### PR TITLE
fix: null creator in ws hooks

### LINKED ISSUE #526: [ws] Deleting an item triggers an error in websockets
Screenshot 2023-07-31 at 15 39 02

The error makes sense because we're not joining creators when getting the descendants (to be deleted)

### PR DESCRIPTION
**Pull request by pyphilia**
This error happens for the following case:

- A > B > C with a membership for each of them for another member Bob
- Removing B, by cascade all the memberships of B and C get deleted
- Since A still have a membership, it triggers the websockets "shared items"
- But since C is get via `getDescendants` which does not return the creator, it fails

In this PR:
- I've added `null` to item's creator and itemMembership's creator
- This highlighted the ws hooks that needed more check on these fields
- added a test
- added postHook for move 

close #526

### CODE REVIEW

File: src/services/item/service.ts [hunk 1]
```diff
@@ -323,6 +323,13 @@ export class ItemService {
```
Comment (dialexo) [inline src/services/item/service.ts:323]: Should we run the prehook here as well?

File: src/services/item/ws/hooks.ts [hunk 2]
```diff
@@ -94,9 +96,9 @@ function registerMemberItemsTopic(websockets: WebsocketService, itemService: Ite
   // on create, notify own items of creator with new item IF path is root
   itemService.hooks.setPostHook('create', async (actor, repositories, { item }) => {
     const parentId = getParentFromPath(item.path);
-    if (parentId === undefined) {
+    if (parentId === undefined && actor) {
       // root item, notify creator
-      websockets.publish(memberItemsTopic, item.creator.id, OwnItemsEvent('create', item));
+      websockets.publish(memberItemsTopic, actor.id, OwnItemsEvent('create', item));
```
Comment (dialexo) [inline src/services/item/ws/hooks.ts:101]: Is `actor` always the creator here? So shouldn't it simply check `if (parentId === undefined && item.creator)`?

File: src/services/item/ws/hooks.ts [hunk 3]
```diff
@@ -125,9 +127,12 @@ function registerMemberItemsTopic(websockets: WebsocketService, itemService: Ite
   // - notify own items of creator of deleted item IF path is root
   // - notify members that have memberships on this item of delete
   //   (before with prehook, otherwise memberships lost on cascade from db!)
+  // todo: currently items can be hard deleted without going to the trash
+  // --> preventing this behavior leads to delete the following code
```
Comment (dialexo) [inline src/services/item/ws/hooks.ts:131]: I don't think we necessarily need to remove the posthook even with the recycle bin? E.g. it should still be true that if an item is recycled then permanently deleted, the change should be broadcasted?

**Review by dialexo — CHANGES_REQUESTED** [review]
Let me know what you think :beer:

**Review by dialexo — APPROVED** [review]
