### PR TITLE
fix: optimize get item parents

### LINKED ISSUE #2003: Optimize GET /parents

### PR DESCRIPTION
**Pull request by pyphilia**
Optimize sql query.

TO REBASE ON https://github.com/graasp/graasp/pull/2004

close #2003

### CODE REVIEW

File: src/services/item/item.repository.ts [hunk 1]
```diff
@@ -277,6 +279,82 @@ export class ItemRepository {
...
+
+    const result = dbConnection
+      .select()
+      .from(itemTree)
+      .leftJoin(imTree, isAncestorOrSelf(imTree.itemPath, itemTree.path))
+      .leftJoin(ivTree, isAncestorOrSelf(ivTree.itemPath, itemTree.path))
+      .where(conditions)
+      .orderBy(asc(sql`nlevel(path)`));
+
+    return (await result).map(({ item_tree }) => ({
```
Comment (spaenleh) [inline src/services/item/item.repository.ts]: I am not a big fan of doing the await in parenthesis like this. I think for legibility it would be better to directly await the result. Maybe add a comment that tells why we await here and not in other queries in this function.

**Review by spaenleh — APPROVED** [review]
Very interesting ! I let you do the proper rebasing once you have merged the depending PR.
