### PR TITLE
fix: order descendants by default

### LINKED ISSUE #860: order descendants
Improve ordering of descendants (still flat), set `true` by default.

### PR DESCRIPTION
**Pull request by pyphilia**
fix #860

### CODE REVIEW

File: src/services/item/utils.ts [hunk 1]
```diff
@@ -59,6 +59,28 @@ export const sortChildrenWith = (idsOrder: string[]) => (stElem: Item, ndElem: I
   return stElem.createdAt.getTime() - ndElem.createdAt.getTime();
 };
 
+const getDirectChildren = (descendants: Item[], parentItem: Item): Item[] => {
+  return descendants.filter((child) => isChildOf(child.path, parentItem.path));
+};
```
Comment (pyphilia) [inline src/services/item/utils.ts:64]: Remove and use directly in below function.

**Review by spaenleh — APPROVED** [review]
Looks good !
