### PR TITLE
fix: sanitize html on upload and import

### LINKED ISSUE #1652: Sanitize html on upload

### PR DESCRIPTION
**Pull request by pyphilia**
close #1652

### CODE REVIEW

File: src/services/file/sanitize.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    },
+  });
+}
+
+export function sanitizeHtml(content: string): string {
+  return sanitize(content);
+}
+
+export function createSanitizedFile(
+  file,
```
Comment (spaenleh) [inline src/services/file/sanitize.ts:41]: Can we set a type for this parameter ?

File: src/services/file/sanitize.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+      rejects(err);
+    });
+
+    file.on('close', async function () {
+      const content = await readFile(tmpFile, {
+        encoding: 'utf8',
+        flag: 'r',
+      });
+
+      const readable = Readable.from(sanitizeFn(content));
```
Comment (spaenleh) [inline src/services/file/sanitize.ts:59]: Is it possible to stream the sanitization ? Maybe not.

**Review by ReidyT — APPROVED** [review]
LGTM really good fix! I agree with the comments of Basile 😶‍🌫️
